Repository kowainik/prolens, pull requests merged in 2020-10, with the labels that each got.

#10 [#1] Initial implementation of Lens
  .github/workflows/ci.yml
  src/Prolens.hs
  test/Spec.hs
Labels: enhancement

#15 [#5] Add tests
  prolens.cabal
  test/Spec.hs
  test/Test/Data.hs
  test/Test/Prolens.hs
Labels: tests

#17 [#4] Add lens operators
  src/Prolens.hs
  test/Test/Prolens.hs
Labels: enhancement

#18 [#6] Add inspection-testing
  prolens.cabal
  src/Prolens.hs
  test/Spec.hs
  test/Test/Data.hs
  test/Test/Prolens/Inspection.hs
Labels: tests

#19 [#3] Configure proper CI
  .github/workflows/ci.yml
  prolens.cabal
  src/Prolens.hs
  stack.yaml
Labels: CI

#21 [#14] Add lens laws tests
  prolens.cabal
  test/Spec.hs
  test/Test/Data.hs
  test/Test/Prolens/Property.hs
Labels: tests

#22 [#20] Swap lens setter args
  src/Prolens.hs
  test/Test/Data.hs
Labels: refactoring

#23 [#11] Rename type variables in types to more meaningful
  src/Prolens.hs
Labels: documentation, enhancement

#24 [#7] Add typeclasses law tests
  src/Prolens.hs
  test/Spec.hs
  test/Test/Data.hs
  test/Test/Prolens/Property.hs
Labels: tests

#27 [#8] Implement Prisms
  src/Prolens.hs
  test/Test/Data.hs
  test/Test/Prolens.hs
Labels: enhancement, idea :bulb:

#29 [#25] Rename 'Profunctor' typeclass variables for better clarity
  src/Prolens.hs
Labels: refactoring

#30 [#12] Write Haddock documentation
  .github/workflows/ci.yml
  prolens.cabal
  src/Prolens.hs
  stack.yaml
  test/Doctest.hs
Labels: documentation

#32 [#2] Write project description
  README.md
Labels: documentation

#33 [#9] Implement Traversal
  src/Prolens.hs
Labels: enhancement

#34 [#28] Performance improvents around prisms
  src/Prolens.hs
  test/Doctest.hs
  test/Spec.hs
  test/Test/Data.hs
  test/Test/Prolens/Inspection.hs
Labels: enhancement, tests

#35 [#31] Add standard lenses and prisms
  src/Prolens.hs
Labels: enhancement

#38 [#37] Add more instances for Fun and Forget
  src/Prolens.hs
Labels: enhancement

#36 Add more Haddock docs
  README.md
  prolens.cabal
  src/Prolens.hs
Labels: documentation

#42 Forget Profunctor property tests
  test/Test/Data.hs
  test/Test/Prolens/Property.hs
Labels: hacktoberfest-accepted, tests

#45 Refactor Profuctor law tests
  test/Test/Prolens/Property.hs
Labels: hacktoberfest-accepted, refactoring, tests

#47 [#46] Document typeclasses laws
  src/Prolens.hs
Labels: documentation

#43 Add Monoidal (->) tests
  test/Test/Prolens/Property.hs
Labels: hacktoberfest-accepted, tests
